export const FETCH_SHIPMENT_SUCCESS = 'FETCH_SHIPMENT_SUCCESS';
export const FETCH_SHIPMENT_ERROR = 'FETCH_SHIPMENT_ERROR';
export const FETCH_SINGLE_SHIPMENT_SUCCESS = 'FETCH_SINGLE_SHIPMENT_SUCCESS';
export const FETCH_SINGLE_SHIPMENT_ERROR = 'FETCH_SINGLE_SHIPMENT_ERROR';
export const UPDATE_SHIPMENT_SUCCESS = 'UPDATE_SHIPMENT_SUCCESS';
export const UPDATE_SHIPMENT_ERROR = 'UPDATE_SHIPMENT_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const FETCH_BIKERS_SUCCESS = 'FETCH_BIKERS_SUCCESS';
export const FETCH_BIKERS_ERROR = 'FETCH_BIKERS_ERROR';
